const CONFIG={"id":271,"slug":"sos-roteador-wifi","name":"SOS Roteador Wi-Fi","description":"Siga verificações externas para energia, conexão, alcance e configuração básica do roteador.","category":"Tecnologia","featured":false,"mode":"sos","key":"tecnologia","content":["não liga","funciona e para","faz ruído","apresenta falha de conexão","resultado irregular","aquece ou cheira diferente"]};
const DATA=["não liga|Teste outra tomada com um aparelho seguro|Confira fonte e conector sem abrir o roteador|Use somente fonte compatível indicada pelo fabricante","rede Wi-Fi sumiu|Observe os LEDs e aguarde a inicialização|Confira se o Wi-Fi foi desativado por botão ou configuração|Reinicie uma vez e consulte o manual do modelo","conecta mas não navega|Teste mais de um dispositivo|Confira cabos entre modem e roteador|Consulte o status da operadora antes de restaurar configurações","internet lenta|Faça medição perto do roteador e por cabo quando possível|Pause downloads e compare horários|Registre resultados antes de falar com a operadora","conexão cai|Observe horário, distância e dispositivos afetados|Afaste o roteador de obstáculos e fontes de interferência|Atualize o firmware somente pelo canal oficial","só um aparelho falha|Esqueça e reconecte a rede nesse aparelho|Confira data, IP automático e atualização do sistema|Não redefina o roteador se os demais funcionam"];
const byId=id=>document.getElementById(id);
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const fmt=value=>Number(value).toLocaleString('pt-BR',{maximumFractionDigits:4});
function clearResult(){const old=byId('out');if(old)old.remove()}
function output(html){clearResult();byId('tool').insertAdjacentHTML('beforeend','<div id="out" class="result">'+html+'</div>')}
function fields(items,type='text'){
 return '<div class="fields">'+items.map((item,index)=>{const spec=typeof item==='string'?{label:item}:item;const long=/perguntas|resumo|discuss|decis|delibera|ingredientes|preparo|observa|descri|orienta|impacto|alternativa|competência|critério/i.test(spec.label);const control=long?'<textarea id="f'+index+'" rows="3">'+esc(spec.value||'')+'</textarea>':'<input id="f'+index+'" type="'+(spec.type||type)+'" step="any" value="'+esc(spec.value||'')+'">';return '<label>'+esc(spec.label)+control+'</label>'}).join('')+'</div>'
}
function numbers(count){const values=[];for(let i=0;i<count;i++)values.push(Number(byId('f'+i).value));return values}
function invalid(message){output('<p class="alert">'+esc(message)+'</p>')}
function calculator(){
 const definitions={
  energia:[{label:'Potência do aparelho (W)'},{label:'Horas de uso por dia'},{label:'Dias de uso no mês'},{label:'Tarifa informada (R$/kWh)'}],
  volumetrico:[{label:'Comprimento (cm)'},{label:'Largura (cm)'},{label:'Altura (cm)'},{label:'Fator cúbico informado (cm³/kg)',value:'6000'}],
  ritmo:[{label:'Distância (km)'},{label:'Tempo total (min)'}],
  diluicao:[{label:'Concentração inicial'},{label:'Volume inicial (mL)'},{label:'Concentração final desejada'}],
  bateria:[{label:'Tensão nominal (V)'},{label:'Capacidade (Ah)'},{label:'Corrente de carga (A)'},{label:'Eficiência estimada (%)',value:'85'}],
  impressao:[{label:'Filamento usado (g)'},{label:'Preço do filamento (R$/kg)'},{label:'Tempo de impressão (h)'},{label:'Custo de máquina (R$/h)'},{label:'Energia medida/estimada (kWh)'},{label:'Tarifa informada (R$/kWh)'}],
  cortina:[{label:'Largura a cobrir (cm)'},{label:'Fator de franzido',value:'2'},{label:'Altura pronta (cm)'},{label:'Soma de barras e cabeçalho (cm)'}],
  presenca:[{label:'Presenças'},{label:'Encontros contabilizados'}],
  voluntariado:[{label:'Pessoas'},{label:'Horas por pessoa e dia'},{label:'Dias de atividade'}],
  ponderada:[{label:'Nota 1'},{label:'Peso 1'},{label:'Nota 2'},{label:'Peso 2'}]
 };
 const def=definitions[CONFIG.formula];byId('tool').innerHTML=fields(def,'number')+'<button id="run">Calcular</button>';
 byId('run').onclick=()=>{const v=numbers(def.length);if(v.some(x=>!Number.isFinite(x)))return invalid('Preencha todos os campos com números válidos.');let lines=[];
  switch(CONFIG.formula){
   case'energia':if(v[0]<0||v[1]<0||v[2]<0||v[3]<0)return invalid('Use valores iguais ou maiores que zero.');{const kwh=v[0]/1000*v[1]*v[2];lines=['Consumo estimado: '+fmt(kwh)+' kWh','Custo com a tarifa informada: R$ '+fmt(kwh*v[3])]}break;
   case'volumetrico':if(v.some(x=>x<=0))return invalid('Dimensões e fator cúbico devem ser maiores que zero.');{const volume=v[0]*v[1]*v[2];lines=['Volume: '+fmt(volume/1000000)+' m³','Peso volumétrico com o fator informado: '+fmt(volume/v[3])+' kg']}break;
   case'ritmo':if(v[0]<=0||v[1]<=0)return invalid('Distância e tempo devem ser maiores que zero.');{const pace=v[1]/v[0],min=Math.floor(pace),sec=Math.round((pace-min)*60);lines=['Ritmo médio: '+min+':'+String(sec===60?0:sec).padStart(2,'0')+' min/km','Velocidade média: '+fmt(v[0]/(v[1]/60))+' km/h']}break;
   case'diluicao':if(v.some(x=>x<=0))return invalid('Concentrações e volume devem ser maiores que zero.');if(v[2]>v[0])return invalid('Para uma diluição simples, a concentração final não pode superar a inicial.');{const finalVolume=v[0]*v[1]/v[2];lines=['Volume final: '+fmt(finalVolume)+' mL','Volume de diluente: '+fmt(finalVolume-v[1])+' mL']}break;
   case'bateria':if(v[0]<=0||v[1]<=0||v[2]<=0||v[3]<=0||v[3]>100)return invalid('Use valores positivos e eficiência entre 0 e 100%.');lines=['Energia nominal: '+fmt(v[0]*v[1])+' Wh','Tempo teórico ajustado: '+fmt(v[1]/(v[2]*(v[3]/100)))+' h'];break;
   case'impressao':if(v.some(x=>x<0))return invalid('Os custos e consumos não podem ser negativos.');{const material=v[0]/1000*v[1],machine=v[2]*v[3],energy=v[4]*v[5];lines=['Material: R$ '+fmt(material),'Máquina: R$ '+fmt(machine),'Energia: R$ '+fmt(energy),'Total direto: R$ '+fmt(material+machine+energy)]}break;
   case'cortina':if(v.some(x=>x<0)||v[0]===0||v[1]===0||v[2]===0)return invalid('Largura, fator e altura devem ser maiores que zero.');lines=['Largura total de tecido: '+fmt(v[0]*v[1])+' cm','Altura de corte: '+fmt(v[2]+v[3])+' cm'];break;
   case'presenca':if(v[1]<=0||v[0]<0||v[0]>v[1])return invalid('Presenças devem ficar entre zero e o total de encontros.');lines=['Percentual de presença: '+fmt(v[0]/v[1]*100)+'%','Faltas: '+fmt(v[1]-v[0])];break;
   case'voluntariado':if(v.some(x=>x<0))return invalid('Use valores iguais ou maiores que zero.');lines=['Horas totais registradas: '+fmt(v[0]*v[1]*v[2])+' h'];break;
   default:if(v[1]<0||v[3]<0||v[1]+v[3]===0)return invalid('Os pesos devem ser positivos e a soma não pode ser zero.');lines=['Média ponderada: '+fmt((v[0]*v[1]+v[2]*v[3])/(v[1]+v[3]))]
  }
  output('<p class="eyebrow">RESULTADO</p>'+lines.map(x=>'<p>'+esc(x)+'</p>').join('')+'<p class="alert">Resultado informativo: confira unidades, premissas e regras da fonte indicada.</p>')
 }
}
function converter(){
 const units={pressao:['Pa','kPa','bar','atm'],temperatura:['°C','°F','K'],cozinha:['mL','L','colher de sopa','colher de chá'],bases:['Decimal','Binário','Hexadecimal'],angulos:['graus','radianos','grados'],energia:['kcal','J'],internet:['Mbit/s','MB/s'],densidade:['kg/m³','g/cm³'],torque:['N·m','kgf·m'],pixels:['px','cm']}[CONFIG.formula];
 const extra=CONFIG.formula==='pixels'?'<label>Resolução (PPI)<input id="ppi" type="number" min="0" step="any" value="300"></label>':'';
 byId('tool').innerHTML='<div class="fields"><label>Valor<input id="value" type="'+(CONFIG.formula==='bases'?'text':'number')+'" step="any" value="1"></label><label>De<select id="from">'+units.map(x=>'<option>'+esc(x)+'</option>').join('')+'</select></label><label>Para<select id="to">'+units.map(x=>'<option>'+esc(x)+'</option>').join('')+'</select></label>'+extra+'</div><button id="run">Converter</button>';
 byId('run').onclick=()=>{const raw=byId('value').value.trim(),a=byId('from').selectedIndex,b=byId('to').selectedIndex;let result;
  if(CONFIG.formula==='bases'){const patterns=[/^[+-]?\d+$/,/^[+-]?[01]+$/,/^[+-]?[0-9a-f]+$/i];if(!patterns[a].test(raw))return invalid('O valor não é válido para a base de origem.');const decimal=parseInt(raw,[10,2,16][a]);result=b===0?String(decimal):decimal.toString([10,2,16][b]).toUpperCase()}
  else{const value=Number(raw);if(!Number.isFinite(value))return invalid('Informe um número válido.');
   if(CONFIG.formula==='temperatura'){const c=a===0?value:a===1?(value-32)*5/9:value-273.15;if(c < -273.15-1e-9)return invalid('A temperatura informada fica abaixo do zero absoluto.');result=b===0?c:b===1?c*9/5+32:c+273.15}
   else if(CONFIG.formula==='angulos'){const degrees=a===0?value:a===1?value*180/Math.PI:value*0.9;result=b===0?degrees:b===1?degrees*Math.PI/180:degrees/0.9}
   else if(CONFIG.formula==='pixels'){const ppi=Number(byId('ppi').value);if(!Number.isFinite(ppi)||ppi<=0)return invalid('Informe uma resolução PPI maior que zero.');result=a===b?value:a===0?value/ppi*2.54:value/2.54*ppi}
   else{const factors={pressao:[1,1000,100000,101325],cozinha:[1,1000,15,5],energia:[4184,1],internet:[0.125,1],densidade:[0.001,1],torque:[1,9.80665]}[CONFIG.formula];result=value*factors[a]/factors[b]}
  }
  output('<p class="eyebrow">RESULTADO</p><h3>'+esc(typeof result==='number'?fmt(result):result)+' '+esc(byId('to').value)+'</h3><p class="formula">A conversão usa a unidade de origem, a unidade de destino e, quando necessário, a resolução informada.</p>')
 }
}
function checklist(){byId('tool').innerHTML='<div class="checklist">'+DATA.map((item,index)=>'<label class="check-item"><input type="checkbox" data-index="'+index+'"><span>'+esc(item)+'</span></label>').join('')+'</div><div class="result"><strong id="progress">0 de '+DATA.length+' concluídos</strong></div>';const update=()=>{byId('progress').textContent=document.querySelectorAll('.check-item input:checked').length+' de '+DATA.length+' concluídos'};document.querySelectorAll('.check-item input').forEach(item=>item.addEventListener('change',update))}
function glossary(){byId('tool').innerHTML='<label>Buscar termo<input id="search" type="search" placeholder="Digite um termo"></label><div id="cards" class="cards"></div>';const normalize=s=>s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');const draw=()=>{const query=normalize(byId('search').value);byId('cards').innerHTML=DATA.filter(item=>normalize(item[0]).includes(query)||normalize(item[1]).includes(query)).map(item=>'<article><h3>'+esc(item[0])+'</h3><p>'+esc(item[1])+'</p></article>').join('')||'<p>Nenhum termo encontrado.</p>'};byId('search').addEventListener('input',draw);draw()}
function generator(){byId('tool').innerHTML=fields(DATA)+'<button id="run">Gerar documento</button>';byId('run').onclick=()=>{const values=DATA.map((label,index)=>byId('f'+index).value.trim()||'não informado');const text=CONFIG.name.toUpperCase()+'\n\n'+DATA.map((label,index)=>label+': '+values[index]).join('\n')+'\n\nDocumento de trabalho — revise nomes, datas, permissões e exigências aplicáveis.';output('<p class="eyebrow">DOCUMENTO GERADO</p><pre class="output">'+esc(text)+'</pre><button id="copy">Copiar texto</button>');byId('copy').onclick=async()=>{try{await navigator.clipboard.writeText(text);byId('copy').textContent='Copiado'}catch{byId('copy').textContent='Selecione o texto para copiar'}}}}
function sos(){const cases=DATA.map(row=>row.split('|'));byId('tool').innerHTML='<label>Sintoma observado<select id="choice">'+cases.map((item,index)=>'<option value="'+index+'">'+esc(item[0])+'</option>').join('')+'</select></label><button id="run">Ver triagem</button>';byId('run').onclick=()=>{const item=cases[Number(byId('choice').value)];output('<p class="eyebrow">TRIAGEM CONSERVADORA</p><h3>'+esc(item[0])+'</h3><ol>'+item.slice(1).map(step=>'<li>'+esc(step)+'</li>').join('')+'</ol><p class="alert">Pare imediatamente diante de fumaça, líquido, cheiro de queimado, calor excessivo ou risco elétrico. Não abra equipamento energizado.</p>')}}
function guide(){const cases=DATA.map(row=>row.split('|'));byId('tool').innerHTML='<label>Uso principal<select id="choice">'+cases.map((item,index)=>'<option value="'+index+'">'+esc(item[0])+'</option>').join('')+'</select></label><button id="run">Comparar critérios</button>';byId('run').onclick=()=>{const item=cases[Number(byId('choice').value)];output('<p class="eyebrow">ORIENTAÇÃO PARA COMPARAR</p><h3>'+esc(item[0])+'</h3><p>'+esc(item[1])+'</p><h4>Confira na ficha técnica</h4><ul>'+item.slice(2).map(check=>'<li>'+esc(check)+'</li>').join('')+'</ul><p class="alert">Compatibilidade e manual do modelo prevalecem sobre recomendações gerais.</p>')}}
function planner(){byId('tool').innerHTML=fields(DATA.fields)+'<button id="run">Montar plano</button>';byId('run').onclick=()=>{const values=DATA.fields.map((label,index)=>byId('f'+index).value.trim()||'não informado');output('<p class="eyebrow">PLANO INICIAL</p><dl>'+DATA.fields.map((label,index)=>'<dt>'+esc(label)+'</dt><dd>'+esc(values[index])+'</dd>').join('')+'</dl><ol>'+DATA.steps.map(step=>'<li>'+esc(step)+'</li>').join('')+'</ol><p class="alert">Revise o plano depois do primeiro ciclo e adapte à realidade local.</p>')}}
({calc:calculator,converter,checklist,glossary,generator,sos,guide,planner}[CONFIG.mode]||planner)();