'use strict';
const assert = require('node:assert/strict');
const app = require('./app.js');
let checks = 0;
function test(name, fn) { fn(); checks += 1; process.stdout.write('✓ ' + name + '\n'); }
test('possui oito rotas distintas', () => assert.equal(Object.keys(app.CASES).length, 8));
test('cada rota tem quatro verificações', () => Object.values(app.CASES).forEach((plan) => assert.equal(plan.checks.length, 4)));
test('cada rota traz teste e ação a evitar', () => Object.values(app.CASES).forEach((plan) => { assert.ok(plan.test); assert.ok(plan.avoid); }));
test('cada rota cita fonte cadastrada', () => Object.values(app.CASES).forEach((plan) => plan.sources.forEach((id) => assert.ok(app.SOURCES[id]))));
test('todas as fontes usam HTTPS', () => Object.values(app.SOURCES).forEach((source) => assert.match(source.url, /^https:\/\//)));
test('risco sempre prevalece sobre sintoma', () => assert.equal(app.getPlan('slow', true), app.RISK));
test('rota normal preserva sintoma', () => assert.equal(app.getPlan('slow', false), app.CASES.slow));
test('sintoma inválido retorna nulo', () => assert.equal(app.getPlan('xpto', false), null));
test('rota geral diferencia vários aparelhos', () => assert.match(app.CASES.unstableAll.test, /cabo e Wi-Fi/));
test('rota de um aparelho evita reset global', () => assert.match(app.CASES.oneDevice.avoid, /Não restaure o roteador/));
test('rota de alcance pede comparação perto e longe', () => assert.match(app.CASES.weakRoom.test, /posições fixas/));
test('rota de velocidade distingue números', () => assert.match(app.CASES.slow.checks.join(' '), /números distintos/));
test('rota sem internet consulta provedor antes de configuração', () => assert.match(app.CASES.allOffline.checks[0], /provedor/));
test('rota de rede ausente compara outro aparelho', () => assert.match(app.CASES.networkMissing.checks[0], /outro aparelho/));
test('rota de reinício proíbe abrir equipamento', () => assert.match(app.CASES.restarts.checks.join(' '), /não abra/));
test('bloco de risco proíbe religar', () => assert.match(app.RISK.checks.join(' '), /não religue/i));
test('nenhuma rota recomenda reset de fábrica', () => Object.values(app.CASES).forEach((plan) => assert.doesNotMatch(plan.checks.join(' '), /faça reset|restaure de fábrica/i)));
test('nenhuma rota prescreve fonte substituta genérica', () => Object.values(app.CASES).forEach((plan) => assert.doesNotMatch(plan.checks.join(' '), /qualquer fonte|mesma tensão basta/i)));
test('escape protege HTML', () => assert.equal(app.escapeHtml('<a>&"'), '&lt;a&gt;&amp;&quot;'));
test('renderização inclui proteção de link externo', () => assert.match(app.renderPlan(app.CASES.slow), /target="_blank" rel="noopener"/));
test('renderização inclui teste e evite', () => { const html = app.renderPlan(app.CASES.slow); assert.match(html, /Como comparar/); assert.match(html, /Evite/); });
test('renderização de risco exibe PARE', () => assert.match(app.renderPlan(app.RISK), />PARE</));
test('renderização inválida é segura', () => assert.match(app.renderPlan(null), /Selecione um sintoma válido/));
test('fontes usadas correspondem exatamente ao catálogo', () => { const used = new Set(Object.values(app.CASES).flatMap((plan) => plan.sources).concat(app.RISK.sources)); assert.deepEqual([...used].sort(), Object.keys(app.SOURCES).sort()); });
process.stdout.write('\n' + checks + ' verificações concluídas.\n');
